// Code generated by "stringer -output=zactiontype_strings.go -type=ActionType -trimprefix=ActionType"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionTypeBlock-4097]
	_ = x[ActionTypePermit-4098]
	_ = x[ActionTypeCalloutTerminating-20483]
	_ = x[ActionTypeCalloutInspection-24580]
	_ = x[ActionTypeCalloutUnknown-16389]
}

const (
	_ActionType_name_0 = "BlockPermit"
	_ActionType_name_1 = "CalloutUnknown"
	_ActionType_name_2 = "CalloutTerminating"
	_ActionType_name_3 = "CalloutInspection"
)

var (
	_ActionType_index_0 = [...]uint8{0, 5, 11}
)

func (i ActionType) String() string {
	switch {
	case 4097 <= i && i <= 4098:
		i -= 4097
		return _ActionType_name_0[_ActionType_index_0[i]:_ActionType_index_0[i+1]]
	case i == 16389:
		return _ActionType_name_1
	case i == 20483:
		return _ActionType_name_2
	case i == 24580:
		return _ActionType_name_3
	default:
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
