// Code generated by "stringer -output=zactiontype_strings.go -type=actionType -trimprefix=actionType"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[actionTypeBlock-4097]
	_ = x[actionTypePermit-4098]
	_ = x[actionTypeCalloutTerminating-20483]
	_ = x[actionTypeCalloutInspection-24580]
	_ = x[actionTypeCalloutUnknown-16389]
}

const (
	_actionType_name_0 = "BlockPermit"
	_actionType_name_1 = "CalloutUnknown"
	_actionType_name_2 = "CalloutTerminating"
	_actionType_name_3 = "CalloutInspection"
)

var (
	_actionType_index_0 = [...]uint8{0, 5, 11}
)

func (i actionType) String() string {
	switch {
	case 4097 <= i && i <= 4098:
		i -= 4097
		return _actionType_name_0[_actionType_index_0[i]:_actionType_index_0[i+1]]
	case i == 16389:
		return _actionType_name_1
	case i == 20483:
		return _actionType_name_2
	case i == 24580:
		return _actionType_name_3
	default:
		return "actionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
