// Code generated by "stringer -output=zfieldtype_strings.go -type=FieldType -trimprefix=Fieldtype"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTypeRawData-0]
	_ = x[FieldTypeIPAddress-1]
	_ = x[FieldTypeFlags-2]
}

const _FieldType_name = "FieldTypeRawDataFieldTypeIPAddressFieldTypeFlags"

var _FieldType_index = [...]uint8{0, 16, 34, 48}

func (i FieldType) String() string {
	if i >= FieldType(len(_FieldType_index)-1) {
		return "FieldType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldType_name[_FieldType_index[i]:_FieldType_index[i+1]]
}
