// Code generated by "stringer -output=zfilterflags_strings.go -type=FilterFlags -trimprefix=FilterFlags"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterFlagsPersistent-1]
	_ = x[FilterFlagsBootTime-2]
	_ = x[FilterFlagsHasProviderContext-4]
	_ = x[FilterFlagsClearActionRight-8]
	_ = x[FilterFlagsPermitIfCalloutUnregistered-16]
	_ = x[FilterFlagsDisabled-32]
	_ = x[FilterFlagsIndexed-64]
}

const (
	_FilterFlags_name_0 = "PersistentBootTime"
	_FilterFlags_name_1 = "HasProviderContext"
	_FilterFlags_name_2 = "ClearActionRight"
	_FilterFlags_name_3 = "PermitIfCalloutUnregistered"
	_FilterFlags_name_4 = "Disabled"
	_FilterFlags_name_5 = "Indexed"
)

var (
	_FilterFlags_index_0 = [...]uint8{0, 10, 18}
)

func (i FilterFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FilterFlags_name_0[_FilterFlags_index_0[i]:_FilterFlags_index_0[i+1]]
	case i == 4:
		return _FilterFlags_name_1
	case i == 8:
		return _FilterFlags_name_2
	case i == 16:
		return _FilterFlags_name_3
	case i == 32:
		return _FilterFlags_name_4
	case i == 64:
		return _FilterFlags_name_5
	default:
		return "FilterFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
