// Code generated by "stringer -output=zfilterenumtype_strings.go -type=FilterEnumType -trimprefix=FilterEnumType"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterEnumTypeFullyContained-0]
	_ = x[FilterEnumTypeOverlapping-1]
}

const _FilterEnumType_name = "FullyContainedOverlapping"

var _FilterEnumType_index = [...]uint8{0, 14, 25}

func (i FilterEnumType) String() string {
	if i >= FilterEnumType(len(_FilterEnumType_index)-1) {
		return "FilterEnumType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterEnumType_name[_FilterEnumType_index[i]:_FilterEnumType_index[i+1]]
}
