// Code generated by "stringer -output=zfilterflags_strings.go -type=filterFlags -trimprefix=filterFlags"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[filterFlagsPersistent-1]
	_ = x[filterFlagsBootTime-2]
	_ = x[filterFlagsHasProviderContext-4]
	_ = x[filterFlagsClearActionRight-8]
	_ = x[filterFlagsPermitIfCalloutUnregistered-16]
	_ = x[filterFlagsDisabled-32]
	_ = x[filterFlagsIndexed-64]
}

const (
	_filterFlags_name_0 = "PersistentBootTime"
	_filterFlags_name_1 = "HasProviderContext"
	_filterFlags_name_2 = "ClearActionRight"
	_filterFlags_name_3 = "PermitIfCalloutUnregistered"
	_filterFlags_name_4 = "Disabled"
	_filterFlags_name_5 = "Indexed"
)

var (
	_filterFlags_index_0 = [...]uint8{0, 10, 18}
)

func (i filterFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _filterFlags_name_0[_filterFlags_index_0[i]:_filterFlags_index_0[i+1]]
	case i == 4:
		return _filterFlags_name_1
	case i == 8:
		return _filterFlags_name_2
	case i == 16:
		return _filterFlags_name_3
	case i == 32:
		return _filterFlags_name_4
	case i == 64:
		return _filterFlags_name_5
	default:
		return "filterFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
