// Code generated by "stringer -output=zlayerflags_strings.go -type=LayerFlags -trimprefix=LayerFlags"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerFlagsKernel-1]
	_ = x[LayerFlagsBuiltin-2]
	_ = x[LayerFlagsClassifyMostly-4]
	_ = x[LayerFlagsBuffered-8]
}

const (
	_LayerFlags_name_0 = "KernelBuiltin"
	_LayerFlags_name_1 = "ClassifyMostly"
	_LayerFlags_name_2 = "Buffered"
)

var (
	_LayerFlags_index_0 = [...]uint8{0, 6, 13}
)

func (i LayerFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LayerFlags_name_0[_LayerFlags_index_0[i]:_LayerFlags_index_0[i+1]]
	case i == 4:
		return _LayerFlags_name_1
	case i == 8:
		return _LayerFlags_name_2
	default:
		return "LayerFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
