// Code generated by "stringer -output=zlayerflags_strings.go -type=fwpmLayerFlags -trimprefix=fwpmLayerFlags"; DO NOT EDIT.

package wf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fwpmLayerFlagsKernel-1]
	_ = x[fwpmLayerFlagsBuiltin-2]
	_ = x[fwpmLayerFlagsClassifyMostly-4]
	_ = x[fwpmLayerFlagsBuffered-8]
}

const (
	_fwpmLayerFlags_name_0 = "KernelBuiltin"
	_fwpmLayerFlags_name_1 = "ClassifyMostly"
	_fwpmLayerFlags_name_2 = "Buffered"
)

var (
	_fwpmLayerFlags_index_0 = [...]uint8{0, 6, 13}
)

func (i fwpmLayerFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _fwpmLayerFlags_name_0[_fwpmLayerFlags_index_0[i]:_fwpmLayerFlags_index_0[i+1]]
	case i == 4:
		return _fwpmLayerFlags_name_1
	case i == 8:
		return _fwpmLayerFlags_name_2
	default:
		return "fwpmLayerFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
