// Code generated by 'go generate'; DO NOT EDIT.

package winfirewall

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modfwpuclnt = windows.NewLazySystemDLL("fwpuclnt.dll")

	procFwpmEngineClose0            = modfwpuclnt.NewProc("FwpmEngineClose0")
	procFwpmEngineOpen0             = modfwpuclnt.NewProc("FwpmEngineOpen0")
	procFwpmFreeMemory0             = modfwpuclnt.NewProc("FwpmFreeMemory0")
	procFwpmLayerCreateEnumHandle0  = modfwpuclnt.NewProc("FwpmLayerCreateEnumHandle0")
	procFwpmLayerDestroyEnumHandle0 = modfwpuclnt.NewProc("FwpmLayerDestroyEnumHandle0")
	procFwpmLayerEnum0              = modfwpuclnt.NewProc("FwpmLayerEnum0")
)

func fwpmEngineClose0(engineHandle windows.Handle) (err error) {
	r1, _, e1 := syscall.Syscall(procFwpmEngineClose0.Addr(), 1, uintptr(engineHandle), 0, 0)
	if r1 != 0 {
		err = errnoErr(e1)
	}
	return
}

func fwpmEngineOpen0(mustBeNil *uint16, authnService authnService, authIdentity *uintptr, session *fwpmSession0, engineHandle *windows.Handle) (err error) {
	r1, _, e1 := syscall.Syscall6(procFwpmEngineOpen0.Addr(), 5, uintptr(unsafe.Pointer(mustBeNil)), uintptr(authnService), uintptr(unsafe.Pointer(authIdentity)), uintptr(unsafe.Pointer(session)), uintptr(unsafe.Pointer(engineHandle)), 0)
	if r1 != 0 {
		err = errnoErr(e1)
	}
	return
}

func fwpmFreeMemory0(p uintptr) {
	syscall.Syscall(procFwpmFreeMemory0.Addr(), 1, uintptr(p), 0, 0)
	return
}

func fwpmLayerCreateEnumHandle0(engineHandle windows.Handle, enumTemplate *fwpmLayerEnumTemplate0, handle *windows.Handle) (err error) {
	r1, _, e1 := syscall.Syscall(procFwpmLayerCreateEnumHandle0.Addr(), 3, uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(handle)))
	if r1 != 0 {
		err = errnoErr(e1)
	}
	return
}

func fwpmLayerDestroyEnumHandle0(engineHandle windows.Handle, enumHandle windows.Handle) (err error) {
	r1, _, e1 := syscall.Syscall(procFwpmLayerDestroyEnumHandle0.Addr(), 2, uintptr(engineHandle), uintptr(enumHandle), 0)
	if r1 != 0 {
		err = errnoErr(e1)
	}
	return
}

func fwpmLayerEnum0(engineHandle windows.Handle, enumHandle windows.Handle, numEntriesRequested uint32, entries ***fwpmLayer0, numEntriesReturned *uint32) (err error) {
	r1, _, e1 := syscall.Syscall6(procFwpmLayerEnum0.Addr(), 5, uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)), 0)
	if r1 != 0 {
		err = errnoErr(e1)
	}
	return
}
